# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tri Ton 
name: Tri Ton
position: PhD Student 
email: huutri99.lhp@gmail.com
description: >-
  I am a second-year PhD student in Electrical Engineering of [KAIST](https://www.kaist.ac.kr/en/), South Korea, advised by [Prof. Chang D Yoo](https://sanctusfactory.com/family.php). I received my B.E. degree in Electrical Engineering from the [Ho Chi Minh City University of Technology](https://hcmut.edu.vn/), Vietnam.

  Email: huutri99.lhp (at) gmail (dot) com

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://triton99.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: DTuanNgo
github_username: triton99
google_scholar: yqzZIBsAAAAJ
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
